questionsAndOptions = {
    "What is the capital of France?": [
        "A. Paris",
        "B. London",
        "C. Berlin",
        "D. Madrid",
    ],
    "Which planet is known as the Red Planet?": [
        "A. Earth",
        "B. Mars",
        "C. Venus",
        "D. Jupiter",
    ],
    "What is the largest ocean on Earth?": [
        "A. Atlantic Ocean",
        "B. Indian Ocean",
        "C. Arctic Ocean",
        "D. Pacific Ocean",
    ],
    "Who wrote 'Hamlet'?": [
        "A. Charles Dickens",
        "B. William Shakespeare",
        "C. Mark Twain",
        "D. Jane Austen",
    ],
    "What is the chemical symbol for water?": ["A. CO2", "B. O2", "C. H2O", "D. NaCl"],
    "Which gas do plants absorb from the atmosphere?": [
        "A. Oxygen",
        "B. Carbon Dioxide",
        "C. Nitrogen",
        "D. Hydrogen",
    ],
    "What is the square root of 64?": ["A. 6", "B. 7", "C. 8", "D. 9"],
    "Who painted the Mona Lisa?": [
        "A. Vincent van Gogh",
        "B. Pablo Picasso",
        "C. Leonardo da Vinci",
        "D. Claude Monet",
    ],
    "Which country is famous for the Great Wall?": [
        "A. India",
        "B. China",
        "C. Japan",
        "D. Russia",
    ],
    "What is the powerhouse of the cell?": [
        "A. Nucleus",
        "B. Mitochondria",
        "C. Ribosome",
        "D. Endoplasmic Reticulum",
    ],
    "How many continents are there?": ["A. 5", "B. 6", "C. 7", "D. 8"],
    "What is the currency of Japan?": ["A. Yen", "B. Won", "C. Rupee", "D. Dollar"],
    "What is the boiling point of water in Celsius?": [
        "A. 90°C",
        "B. 100°C",
        "C. 110°C",
        "D. 120°C",
    ],
    "Which is the longest river in the world?": [
        "A. Amazon River",
        "B. Nile River",
        "C. Yangtze River",
        "D. Mississippi River",
    ],
    "Which organ pumps blood in the human body?": [
        "A. Liver",
        "B. Kidney",
        "C. Heart",
        "D. Lungs",
    ],
    "What is the capital of Italy?": [
        "A. Rome",
        "B. Venice",
        "C. Milan",
        "D. Florence",
    ],
    "Which is the smallest planet in the solar system?": [
        "A. Mercury",
        "B. Mars",
        "C. Venus",
        "D. Neptune",
    ],
    "Who discovered gravity?": [
        "A. Albert Einstein",
        "B. Isaac Newton",
        "C. Galileo Galilei",
        "D. Nikola Tesla",
    ],
    "What is the fastest land animal?": [
        "A. Cheetah",
        "B. Lion",
        "C. Tiger",
        "D. Horse",
    ],
    "What is the capital of Canada?": [
        "A. Toronto",
        "B. Ottawa",
        "C. Vancouver",
        "D. Montreal",
    ],
    "Who invented the telephone?": [
        "A. Alexander Graham Bell",
        "B. Thomas Edison",
        "C. Nikola Tesla",
        "D. Albert Einstein",
    ],
    "Which is the tallest mountain in the world?": [
        "A. K2",
        "B. Kangchenjunga",
        "C. Mount Everest",
        "D. Lhotse",
    ],
    "What is the national animal of India?": [
        "A. Elephant",
        "B. Lion",
        "C. Tiger",
        "D. Peacock",
    ],
    "How many legs does a spider have?": ["A. 6", "B. 8", "C. 10", "D. 12"],
    "Which element has the atomic number 1?": [
        "A. Oxygen",
        "B. Hydrogen",
        "C. Helium",
        "D. Carbon",
    ],
    "What is the capital of Germany?": [
        "A. Berlin",
        "B. Munich",
        "C. Frankfurt",
        "D. Hamburg",
    ],
    "What is the national language of China?": [
        "A. Cantonese",
        "B. Mandarin",
        "C. Hindi",
        "D. English",
    ],
    "Which is the coldest planet in the solar system?": [
        "A. Neptune",
        "B. Uranus",
        "C. Saturn",
        "D. Pluto",
    ],
    "Who developed the theory of relativity?": [
        "A. Isaac Newton",
        "B. Albert Einstein",
        "C. Galileo Galilei",
        "D. Stephen Hawking",
    ],
    "Which is the largest desert in the world?": [
        "A. Gobi",
        "B. Sahara",
        "C. Kalahari",
        "D. Antarctic Desert",
    ],
    "Who was the first man to walk on the moon?": [
        "A. Buzz Aldrin",
        "B. Neil Armstrong",
        "C. Yuri Gagarin",
        "D. Michael Collins",
    ],
    "Which metal is liquid at room temperature?": [
        "A. Mercury",
        "B. Gold",
        "C. Silver",
        "D. Copper",
    ],
    "What is the square of 12?": ["A. 122", "B. 144", "C. 132", "D. 156"],
    "What is the longest bone in the human body?": [
        "A. Femur",
        "B. Humerus",
        "C. Tibia",
        "D. Radius",
    ],
    "Which is the smallest country in the world?": [
        "A. Monaco",
        "B. Vatican City",
        "C. Liechtenstein",
        "D. San Marino",
    ],
    "What does DNA stand for?": [
        "A. Deoxyribonucleic Acid",
        "B. Dinucleic Acid",
        "C. Double Helix Acid",
        "D. Deoxynucleotide Acid",
    ],
    "Which is the largest mammal in the world?": [
        "A. Elephant",
        "B. Blue Whale",
        "C. Giraffe",
        "D. Hippopotamus",
    ],
    "What is the speed of light?": [
        "A. 300,000 km/s",
        "B. 150,000 km/s",
        "C. 450,000 km/s",
        "D. 600,000 km/s",
    ],
}
answer_key = {
    "What is the capital of France?": "A",
    "Which planet is known as the Red Planet?": "B",
    "What is the largest ocean on Earth?": "D",
    "Who wrote 'Hamlet'?": "B",
    "What is the chemical symbol for water?": "C",
    "Which gas do plants absorb from the atmosphere?": "B",
    "What is the square root of 64?": "C",
    "Who painted the Mona Lisa?": "C",
    "Which country is famous for the Great Wall?": "B",
    "What is the powerhouse of the cell?": "B",
    "How many continents are there?": "C",
    "What is the currency of Japan?": "A",
    "What is the boiling point of water in Celsius?": "B",
    "Which is the longest river in the world?": "B",
    "Which organ pumps blood in the human body?": "C",
    "What is the capital of Italy?": "A",
    "Which is the smallest planet in the solar system?": "A",
    "Who discovered gravity?": "B",
    "What is the fastest land animal?": "A",
    "What is the capital of Canada?": "B",
    "Who invented the telephone?": "A",
    "Which is the tallest mountain in the world?": "C",
    "What is the national animal of India?": "C",
    "How many legs does a spider have?": "B",
    "Which element has the atomic number 1?": "B",
    "What is the capital of Germany?": "A",
    "What is the national language of China?": "B",
    "Which is the coldest planet in the solar system?": "A",
    "Who developed the theory of relativity?": "B",
    "Which is the largest desert in the world?": "D",
    "Who was the first man to walk on the moon?": "B",
    "Which metal is liquid at room temperature?": "A",
    "What is the square of 12?": "B",
    "What is the longest bone in the human body?": "A",
    "Which is the smallest country in the world?": "B",
    "What does DNA stand for?": "A",
    "Which is the largest mammal in the world?": "B",
    "What is the speed of light?": "A",
}